version: '3.8'

services:
  beanstalkd:
    container_name: ddev-beanstalkd
    image: schickling/beanstalkd
    restart: "no"
    expose:
      - 11300 # (порт по умолчанию для beanstalkd)
    ports:
      - 11300:11300
    labels:
      com.ddev.site-name: "sitename"
    volumes:
      - ".:/mnt/ddev_config"
  mysql:
    image: mysql:5.7
    container_name: amocrm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - amocrm_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amocrm_golang
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "2020:2020"
    volumes:
      - ./.env:/gelzhuravleva/.env 
    networks:
      - amocrm_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  amocrm_network:
    driver: bridge